/*
 * generated by Xtext 2.32.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class StatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Statement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSumujParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSukcesyParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Statement returns Stat:
		//    Sumuj | Sukcesy
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Sumuj | Sukcesy
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//Sumuj
		public RuleCall getSumujParserRuleCall_0() { return cSumujParserRuleCall_0; }
		
		//Sukcesy
		public RuleCall getSukcesyParserRuleCall_1() { return cSukcesyParserRuleCall_1; }
	}
	public class SumujElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Sumuj");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSUMUJKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDiceexprsumAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDiceexprsumDiceExprSumParserRuleCall_1_0 = (RuleCall)cDiceexprsumAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cSemicolonKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cDiceexprsumAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cDiceexprsumDiceExprSumParserRuleCall_2_1_0 = (RuleCall)cDiceexprsumAssignment_2_1.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Keyword cFullStopKeyword_3_0 = (Keyword)cAlternatives_3.eContents().get(0);
		private final Keyword cCommaKeyword_3_1 = (Keyword)cAlternatives_3.eContents().get(1);
		
		//Sumuj returns SumStatement:
		//    'SUMUJ' diceexprsum+=DiceExprSum ( ';' diceexprsum+=DiceExprSum )* ('.' | ',')?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'SUMUJ' diceexprsum+=DiceExprSum ( ';' diceexprsum+=DiceExprSum )* ('.' | ',')?
		public Group getGroup() { return cGroup; }
		
		//'SUMUJ'
		public Keyword getSUMUJKeyword_0() { return cSUMUJKeyword_0; }
		
		//diceexprsum+=DiceExprSum
		public Assignment getDiceexprsumAssignment_1() { return cDiceexprsumAssignment_1; }
		
		//DiceExprSum
		public RuleCall getDiceexprsumDiceExprSumParserRuleCall_1_0() { return cDiceexprsumDiceExprSumParserRuleCall_1_0; }
		
		//( ';' diceexprsum+=DiceExprSum )*
		public Group getGroup_2() { return cGroup_2; }
		
		//';'
		public Keyword getSemicolonKeyword_2_0() { return cSemicolonKeyword_2_0; }
		
		//diceexprsum+=DiceExprSum
		public Assignment getDiceexprsumAssignment_2_1() { return cDiceexprsumAssignment_2_1; }
		
		//DiceExprSum
		public RuleCall getDiceexprsumDiceExprSumParserRuleCall_2_1_0() { return cDiceexprsumDiceExprSumParserRuleCall_2_1_0; }
		
		//('.' | ',')?
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//'.'
		public Keyword getFullStopKeyword_3_0() { return cFullStopKeyword_3_0; }
		
		//','
		public Keyword getCommaKeyword_3_1() { return cCommaKeyword_3_1; }
	}
	public class SukcesyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Sukcesy");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSUKCESYKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDiceexprsukAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDiceexprsukDiceExprSukParserRuleCall_1_0 = (RuleCall)cDiceexprsukAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cSemicolonKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cDiceexprsukAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cDiceexprsukDiceExprSukParserRuleCall_2_1_0 = (RuleCall)cDiceexprsukAssignment_2_1.eContents().get(0);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Keyword cFullStopKeyword_3_0 = (Keyword)cAlternatives_3.eContents().get(0);
		private final Keyword cCommaKeyword_3_1 = (Keyword)cAlternatives_3.eContents().get(1);
		
		//Sukcesy returns SuccessStatement:
		//    'SUKCESY' diceexprsuk+=DiceExprSuk ( ';' diceexprsuk+=DiceExprSuk )* ('.' | ',')?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'SUKCESY' diceexprsuk+=DiceExprSuk ( ';' diceexprsuk+=DiceExprSuk )* ('.' | ',')?
		public Group getGroup() { return cGroup; }
		
		//'SUKCESY'
		public Keyword getSUKCESYKeyword_0() { return cSUKCESYKeyword_0; }
		
		//diceexprsuk+=DiceExprSuk
		public Assignment getDiceexprsukAssignment_1() { return cDiceexprsukAssignment_1; }
		
		//DiceExprSuk
		public RuleCall getDiceexprsukDiceExprSukParserRuleCall_1_0() { return cDiceexprsukDiceExprSukParserRuleCall_1_0; }
		
		//( ';' diceexprsuk+=DiceExprSuk )*
		public Group getGroup_2() { return cGroup_2; }
		
		//';'
		public Keyword getSemicolonKeyword_2_0() { return cSemicolonKeyword_2_0; }
		
		//diceexprsuk+=DiceExprSuk
		public Assignment getDiceexprsukAssignment_2_1() { return cDiceexprsukAssignment_2_1; }
		
		//DiceExprSuk
		public RuleCall getDiceexprsukDiceExprSukParserRuleCall_2_1_0() { return cDiceexprsukDiceExprSukParserRuleCall_2_1_0; }
		
		//('.' | ',')?
		public Alternatives getAlternatives_3() { return cAlternatives_3; }
		
		//'.'
		public Keyword getFullStopKeyword_3_0() { return cFullStopKeyword_3_0; }
		
		//','
		public Keyword getCommaKeyword_3_1() { return cCommaKeyword_3_1; }
	}
	public class DiceExprSumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DiceExprSum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cPlusSignKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cMulexprAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMulexprMulExprParserRuleCall_1_0 = (RuleCall)cMulexprAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSumruleAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cSumruleRuleSumParserRuleCall_2_1_0 = (RuleCall)cSumruleAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cCommaKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cSumruleAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cSumruleRuleSumParserRuleCall_2_2_1_0 = (RuleCall)cSumruleAssignment_2_2_1.eContents().get(0);
		
		//DiceExprSum returns DiceExprSum:
		//    ('+'|'-')? mulexpr=MulExpr (':' sumrule+=RuleSum (',' sumrule+=RuleSum)*)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('+'|'-')? mulexpr=MulExpr (':' sumrule+=RuleSum (',' sumrule+=RuleSum)*)?
		public Group getGroup() { return cGroup; }
		
		//('+'|'-')?
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'+'
		public Keyword getPlusSignKeyword_0_0() { return cPlusSignKeyword_0_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_0_1() { return cHyphenMinusKeyword_0_1; }
		
		//mulexpr=MulExpr
		public Assignment getMulexprAssignment_1() { return cMulexprAssignment_1; }
		
		//MulExpr
		public RuleCall getMulexprMulExprParserRuleCall_1_0() { return cMulexprMulExprParserRuleCall_1_0; }
		
		//(':' sumrule+=RuleSum (',' sumrule+=RuleSum)*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//':'
		public Keyword getColonKeyword_2_0() { return cColonKeyword_2_0; }
		
		//sumrule+=RuleSum
		public Assignment getSumruleAssignment_2_1() { return cSumruleAssignment_2_1; }
		
		//RuleSum
		public RuleCall getSumruleRuleSumParserRuleCall_2_1_0() { return cSumruleRuleSumParserRuleCall_2_1_0; }
		
		//(',' sumrule+=RuleSum)*
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//','
		public Keyword getCommaKeyword_2_2_0() { return cCommaKeyword_2_2_0; }
		
		//sumrule+=RuleSum
		public Assignment getSumruleAssignment_2_2_1() { return cSumruleAssignment_2_2_1; }
		
		//RuleSum
		public RuleCall getSumruleRuleSumParserRuleCall_2_2_1_0() { return cSumruleRuleSumParserRuleCall_2_2_1_0; }
	}
	public class DiceExprSukElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DiceExprSuk");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cPlusSignKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cMulexprAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMulexprMulExprParserRuleCall_1_0 = (RuleCall)cMulexprAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cColonKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cSuccessruleAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cSuccessruleRuleSukParserRuleCall_2_1_0 = (RuleCall)cSuccessruleAssignment_2_1.eContents().get(0);
		private final Group cGroup_2_2 = (Group)cGroup_2.eContents().get(2);
		private final Keyword cCommaKeyword_2_2_0 = (Keyword)cGroup_2_2.eContents().get(0);
		private final Assignment cSuccessruleAssignment_2_2_1 = (Assignment)cGroup_2_2.eContents().get(1);
		private final RuleCall cSuccessruleRuleSukParserRuleCall_2_2_1_0 = (RuleCall)cSuccessruleAssignment_2_2_1.eContents().get(0);
		
		//DiceExprSuk returns DiceExprSuk:
		//    ('+'|'-')? mulexpr=MulExpr (':' successrule+=RuleSuk (',' successrule+=RuleSuk)*)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('+'|'-')? mulexpr=MulExpr (':' successrule+=RuleSuk (',' successrule+=RuleSuk)*)?
		public Group getGroup() { return cGroup; }
		
		//('+'|'-')?
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'+'
		public Keyword getPlusSignKeyword_0_0() { return cPlusSignKeyword_0_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_0_1() { return cHyphenMinusKeyword_0_1; }
		
		//mulexpr=MulExpr
		public Assignment getMulexprAssignment_1() { return cMulexprAssignment_1; }
		
		//MulExpr
		public RuleCall getMulexprMulExprParserRuleCall_1_0() { return cMulexprMulExprParserRuleCall_1_0; }
		
		//(':' successrule+=RuleSuk (',' successrule+=RuleSuk)*)?
		public Group getGroup_2() { return cGroup_2; }
		
		//':'
		public Keyword getColonKeyword_2_0() { return cColonKeyword_2_0; }
		
		//successrule+=RuleSuk
		public Assignment getSuccessruleAssignment_2_1() { return cSuccessruleAssignment_2_1; }
		
		//RuleSuk
		public RuleCall getSuccessruleRuleSukParserRuleCall_2_1_0() { return cSuccessruleRuleSukParserRuleCall_2_1_0; }
		
		//(',' successrule+=RuleSuk)*
		public Group getGroup_2_2() { return cGroup_2_2; }
		
		//','
		public Keyword getCommaKeyword_2_2_0() { return cCommaKeyword_2_2_0; }
		
		//successrule+=RuleSuk
		public Assignment getSuccessruleAssignment_2_2_1() { return cSuccessruleAssignment_2_2_1; }
		
		//RuleSuk
		public RuleCall getSuccessruleRuleSukParserRuleCall_2_2_1_0() { return cSuccessruleRuleSukParserRuleCall_2_2_1_0; }
	}
	public class MulExprElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MulExpr");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cFormexprAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cFormexprFormParserRuleCall_0_0 = (RuleCall)cFormexprAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Assignment cFormexprAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cFormexprFormParserRuleCall_1_1_0 = (RuleCall)cFormexprAssignment_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_1_2 = (Keyword)cGroup_1.eContents().get(2);
		private final Group cGroup_1_3 = (Group)cGroup_1.eContents().get(3);
		private final Keyword cRazyKeyword_1_3_0 = (Keyword)cGroup_1_3.eContents().get(0);
		private final Assignment cNumAssignment_1_3_1 = (Assignment)cGroup_1_3.eContents().get(1);
		private final RuleCall cNumNumParserRuleCall_1_3_1_0 = (RuleCall)cNumAssignment_1_3_1.eContents().get(0);
		
		//MulExpr returns MulExpr:
		//        formexpr=Form
		//  | '(' formexpr=Form ')' ('razy' num=Num)?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//      formexpr=Form
		//| '(' formexpr=Form ')' ('razy' num=Num)?
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//formexpr=Form
		public Assignment getFormexprAssignment_0() { return cFormexprAssignment_0; }
		
		//Form
		public RuleCall getFormexprFormParserRuleCall_0_0() { return cFormexprFormParserRuleCall_0_0; }
		
		//'(' formexpr=Form ')' ('razy' num=Num)?
		public Group getGroup_1() { return cGroup_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_0() { return cLeftParenthesisKeyword_1_0; }
		
		//formexpr=Form
		public Assignment getFormexprAssignment_1_1() { return cFormexprAssignment_1_1; }
		
		//Form
		public RuleCall getFormexprFormParserRuleCall_1_1_0() { return cFormexprFormParserRuleCall_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_2() { return cRightParenthesisKeyword_1_2; }
		
		//('razy' num=Num)?
		public Group getGroup_1_3() { return cGroup_1_3; }
		
		//'razy'
		public Keyword getRazyKeyword_1_3_0() { return cRazyKeyword_1_3_0; }
		
		//num=Num
		public Assignment getNumAssignment_1_3_1() { return cNumAssignment_1_3_1; }
		
		//Num
		public RuleCall getNumNumParserRuleCall_1_3_1_0() { return cNumNumParserRuleCall_1_3_1_0; }
	}
	public class FormElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Form");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLeftAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLeftDiceParserRuleCall_0_0 = (RuleCall)cLeftAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Assignment cOperatorAssignment_1_0 = (Assignment)cGroup_1.eContents().get(0);
		private final RuleCall cOperatorOperatorParserRuleCall_1_0_0 = (RuleCall)cOperatorAssignment_1_0.eContents().get(0);
		private final Assignment cRightAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cRightNumParserRuleCall_1_1_0 = (RuleCall)cRightAssignment_1_1.eContents().get(0);
		
		//Form returns FormExpr:
		//    left=(Dice) ( operator=Operator right=Num )?
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//left=(Dice) ( operator=Operator right=Num )?
		public Group getGroup() { return cGroup; }
		
		//left=(Dice)
		public Assignment getLeftAssignment_0() { return cLeftAssignment_0; }
		
		//(Dice)
		public RuleCall getLeftDiceParserRuleCall_0_0() { return cLeftDiceParserRuleCall_0_0; }
		
		//( operator=Operator right=Num )?
		public Group getGroup_1() { return cGroup_1; }
		
		//operator=Operator
		public Assignment getOperatorAssignment_1_0() { return cOperatorAssignment_1_0; }
		
		//Operator
		public RuleCall getOperatorOperatorParserRuleCall_1_0_0() { return cOperatorOperatorParserRuleCall_1_0_0; }
		
		//right=Num
		public Assignment getRightAssignment_1_1() { return cRightAssignment_1_1; }
		
		//Num
		public RuleCall getRightNumParserRuleCall_1_1_0() { return cRightNumParserRuleCall_1_1_0; }
	}
	public class SingleDiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SingleDice");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cSidesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cSidesNumParserRuleCall_1_0 = (RuleCall)cSidesAssignment_1.eContents().get(0);
		
		//SingleDice returns SingleDice:
		//    'd' sides=Num
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'d' sides=Num
		public Group getGroup() { return cGroup; }
		
		//'d'
		public Keyword getDKeyword_0() { return cDKeyword_0; }
		
		//sides=Num
		public Assignment getSidesAssignment_1() { return cSidesAssignment_1; }
		
		//Num
		public RuleCall getSidesNumParserRuleCall_1_0() { return cSidesNumParserRuleCall_1_0; }
	}
	public class MultiDiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MultiDice");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cCountAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cCountNumParserRuleCall_0_0 = (RuleCall)cCountAssignment_0.eContents().get(0);
		private final Keyword cDKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cSidesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSidesNumParserRuleCall_2_0 = (RuleCall)cSidesAssignment_2.eContents().get(0);
		
		//MultiDice returns MultiDice:
		//    count=Num 'd' sides=Num
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//count=Num 'd' sides=Num
		public Group getGroup() { return cGroup; }
		
		//count=Num
		public Assignment getCountAssignment_0() { return cCountAssignment_0; }
		
		//Num
		public RuleCall getCountNumParserRuleCall_0_0() { return cCountNumParserRuleCall_0_0; }
		
		//'d'
		public Keyword getDKeyword_1() { return cDKeyword_1; }
		
		//sides=Num
		public Assignment getSidesAssignment_2() { return cSidesAssignment_2; }
		
		//Num
		public RuleCall getSidesNumParserRuleCall_2_0() { return cSidesNumParserRuleCall_2_0; }
	}
	public class DiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Dice");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSingleDiceParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMultiDiceParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Dice returns Dice:
		//    SingleDice | MultiDice
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//SingleDice | MultiDice
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SingleDice
		public RuleCall getSingleDiceParserRuleCall_0() { return cSingleDiceParserRuleCall_0; }
		
		//MultiDice
		public RuleCall getMultiDiceParserRuleCall_1() { return cMultiDiceParserRuleCall_1; }
	}
	public class ExplosionRuleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ExplosionRule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cDodawajKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cOdejmujKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Keyword cWybuchoweKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNumAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNumNumParserRuleCall_2_0 = (RuleCall)cNumAssignment_2.eContents().get(0);
		
		//ExplosionRule returns ExplosionRule:
		//    ('dodawaj' | 'odejmuj') 'wybuchowe' num=Num
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('dodawaj' | 'odejmuj') 'wybuchowe' num=Num
		public Group getGroup() { return cGroup; }
		
		//('dodawaj' | 'odejmuj')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'dodawaj'
		public Keyword getDodawajKeyword_0_0() { return cDodawajKeyword_0_0; }
		
		//'odejmuj'
		public Keyword getOdejmujKeyword_0_1() { return cOdejmujKeyword_0_1; }
		
		//'wybuchowe'
		public Keyword getWybuchoweKeyword_1() { return cWybuchoweKeyword_1; }
		
		//num=Num
		public Assignment getNumAssignment_2() { return cNumAssignment_2; }
		
		//Num
		public RuleCall getNumNumParserRuleCall_2_0() { return cNumNumParserRuleCall_2_0; }
	}
	public class DiceMarkSumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DiceMarkSum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOznaczKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMarkAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMarkMarkParserRuleCall_1_0 = (RuleCall)cMarkAssignment_1.eContents().get(0);
		
		//DiceMarkSum returns DiceMarkSum:
		//    'oznacz' mark=Mark
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'oznacz' mark=Mark
		public Group getGroup() { return cGroup; }
		
		//'oznacz'
		public Keyword getOznaczKeyword_0() { return cOznaczKeyword_0; }
		
		//mark=Mark
		public Assignment getMarkAssignment_1() { return cMarkAssignment_1; }
		
		//Mark
		public RuleCall getMarkMarkParserRuleCall_1_0() { return cMarkMarkParserRuleCall_1_0; }
	}
	public class DiceDiscSumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DiceDiscSum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOdrzucKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDiscardAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDiscardDiscardParserRuleCall_1_0 = (RuleCall)cDiscardAssignment_1.eContents().get(0);
		
		//DiceDiscSum returns DiceDiscSum:
		//    'odrzuc' discard=Discard
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'odrzuc' discard=Discard
		public Group getGroup() { return cGroup; }
		
		//'odrzuc'
		public Keyword getOdrzucKeyword_0() { return cOdrzucKeyword_0; }
		
		//discard=Discard
		public Assignment getDiscardAssignment_1() { return cDiscardAssignment_1; }
		
		//Discard
		public RuleCall getDiscardDiscardParserRuleCall_1_0() { return cDiscardDiscardParserRuleCall_1_0; }
	}
	public class DiceRerollSumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DiceRerollSum");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPrzerzucKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cRerollAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRerollRerollParserRuleCall_1_0 = (RuleCall)cRerollAssignment_1.eContents().get(0);
		
		//DiceRerollSum returns DiceRerollSum:
		//    'przerzuc' reroll=Reroll
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'przerzuc' reroll=Reroll
		public Group getGroup() { return cGroup; }
		
		//'przerzuc'
		public Keyword getPrzerzucKeyword_0() { return cPrzerzucKeyword_0; }
		
		//reroll=Reroll
		public Assignment getRerollAssignment_1() { return cRerollAssignment_1; }
		
		//Reroll
		public RuleCall getRerollRerollParserRuleCall_1_0() { return cRerollRerollParserRuleCall_1_0; }
	}
	public class RuleSumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RuleSum");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cExplosionRuleParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDiceMarkSumParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDiceDiscSumParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cDiceRerollSumParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//RuleSum returns SumRule:
		//    ExplosionRule
		//  | DiceMarkSum
		//  | DiceDiscSum
		//  | DiceRerollSum
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//  ExplosionRule
		//| DiceMarkSum
		//| DiceDiscSum
		//| DiceRerollSum
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//ExplosionRule
		public RuleCall getExplosionRuleParserRuleCall_0() { return cExplosionRuleParserRuleCall_0; }
		
		//DiceMarkSum
		public RuleCall getDiceMarkSumParserRuleCall_1() { return cDiceMarkSumParserRuleCall_1; }
		
		//DiceDiscSum
		public RuleCall getDiceDiscSumParserRuleCall_2() { return cDiceDiscSumParserRuleCall_2; }
		
		//DiceRerollSum
		public RuleCall getDiceRerollSumParserRuleCall_3() { return cDiceRerollSumParserRuleCall_3; }
	}
	public class SuccessThresholdElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SuccessThreshold");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSukcesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cWiecejNizKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Keyword cMniejNizKeyword_1_1 = (Keyword)cAlternatives_1.eContents().get(1);
		private final Assignment cNumAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNumNumParserRuleCall_2_0 = (RuleCall)cNumAssignment_2.eContents().get(0);
		
		//SuccessThreshold returns SuccessThreshold:
		//    'sukces' ('wiecej niz' | 'mniej niz') num=Num
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'sukces' ('wiecej niz' | 'mniej niz') num=Num
		public Group getGroup() { return cGroup; }
		
		//'sukces'
		public Keyword getSukcesKeyword_0() { return cSukcesKeyword_0; }
		
		//('wiecej niz' | 'mniej niz')
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'wiecej niz'
		public Keyword getWiecejNizKeyword_1_0() { return cWiecejNizKeyword_1_0; }
		
		//'mniej niz'
		public Keyword getMniejNizKeyword_1_1() { return cMniejNizKeyword_1_1; }
		
		//num=Num
		public Assignment getNumAssignment_2() { return cNumAssignment_2; }
		
		//Num
		public RuleCall getNumNumParserRuleCall_2_0() { return cNumNumParserRuleCall_2_0; }
	}
	public class SuccessMultiplierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SuccessMultiplier");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSukcesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNumAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNumNumParserRuleCall_1_0 = (RuleCall)cNumAssignment_1.eContents().get(0);
		private final Keyword cRazyKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMultAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMultNumParserRuleCall_3_0 = (RuleCall)cMultAssignment_3.eContents().get(0);
		
		//SuccessMultiplier returns SuccessMultiplier:
		//    'sukces' num=Num 'razy' mult=Num
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'sukces' num=Num 'razy' mult=Num
		public Group getGroup() { return cGroup; }
		
		//'sukces'
		public Keyword getSukcesKeyword_0() { return cSukcesKeyword_0; }
		
		//num=Num
		public Assignment getNumAssignment_1() { return cNumAssignment_1; }
		
		//Num
		public RuleCall getNumNumParserRuleCall_1_0() { return cNumNumParserRuleCall_1_0; }
		
		//'razy'
		public Keyword getRazyKeyword_2() { return cRazyKeyword_2; }
		
		//mult=Num
		public Assignment getMultAssignment_3() { return cMultAssignment_3; }
		
		//Num
		public RuleCall getMultNumParserRuleCall_3_0() { return cMultNumParserRuleCall_3_0; }
	}
	public class SuccessBasicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SuccessBasic");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSukcesKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Keyword cSukcesKeyword_1_0 = (Keyword)cAlternatives_1.eContents().get(0);
		private final Assignment cNumAssignment_1_1 = (Assignment)cAlternatives_1.eContents().get(1);
		private final RuleCall cNumNumParserRuleCall_1_1_0 = (RuleCall)cNumAssignment_1_1.eContents().get(0);
		
		//SuccessBasic returns SuccessBasic:
		//    'sukces' ('sukces' | num=Num)
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'sukces' ('sukces' | num=Num)
		public Group getGroup() { return cGroup; }
		
		//'sukces'
		public Keyword getSukcesKeyword_0() { return cSukcesKeyword_0; }
		
		//('sukces' | num=Num)
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//'sukces'
		public Keyword getSukcesKeyword_1_0() { return cSukcesKeyword_1_0; }
		
		//num=Num
		public Assignment getNumAssignment_1_1() { return cNumAssignment_1_1; }
		
		//Num
		public RuleCall getNumNumParserRuleCall_1_1_0() { return cNumNumParserRuleCall_1_1_0; }
	}
	public class DiceMarkSukElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DiceMarkSuk");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOznaczKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMarkAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMarkMarkParserRuleCall_1_0 = (RuleCall)cMarkAssignment_1.eContents().get(0);
		
		//DiceMarkSuk returns DiceMarkSuk:
		//    'oznacz' mark=Mark
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'oznacz' mark=Mark
		public Group getGroup() { return cGroup; }
		
		//'oznacz'
		public Keyword getOznaczKeyword_0() { return cOznaczKeyword_0; }
		
		//mark=Mark
		public Assignment getMarkAssignment_1() { return cMarkAssignment_1; }
		
		//Mark
		public RuleCall getMarkMarkParserRuleCall_1_0() { return cMarkMarkParserRuleCall_1_0; }
	}
	public class DiceDiscSukElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DiceDiscSuk");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOdrzucKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDiscardAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDiscardDiscardParserRuleCall_1_0 = (RuleCall)cDiscardAssignment_1.eContents().get(0);
		
		//DiceDiscSuk returns DiceDiscSuk:
		//    'odrzuc' discard=Discard
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'odrzuc' discard=Discard
		public Group getGroup() { return cGroup; }
		
		//'odrzuc'
		public Keyword getOdrzucKeyword_0() { return cOdrzucKeyword_0; }
		
		//discard=Discard
		public Assignment getDiscardAssignment_1() { return cDiscardAssignment_1; }
		
		//Discard
		public RuleCall getDiscardDiscardParserRuleCall_1_0() { return cDiscardDiscardParserRuleCall_1_0; }
	}
	public class DiceRerollSukElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DiceRerollSuk");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPrzerzucKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cRerollAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cRerollRerollParserRuleCall_1_0 = (RuleCall)cRerollAssignment_1.eContents().get(0);
		
		//DiceRerollSuk returns DiceRerollSuk:
		//    'przerzuc' reroll=Reroll
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'przerzuc' reroll=Reroll
		public Group getGroup() { return cGroup; }
		
		//'przerzuc'
		public Keyword getPrzerzucKeyword_0() { return cPrzerzucKeyword_0; }
		
		//reroll=Reroll
		public Assignment getRerollAssignment_1() { return cRerollAssignment_1; }
		
		//Reroll
		public RuleCall getRerollRerollParserRuleCall_1_0() { return cRerollRerollParserRuleCall_1_0; }
	}
	public class RuleSukElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RuleSuk");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSuccessThresholdParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSuccessMultiplierParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cSuccessBasicParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cDiceMarkSukParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cDiceDiscSukParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cDiceRerollSukParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//RuleSuk returns SuccessRule:
		//    SuccessThreshold
		//  | SuccessMultiplier
		//  | SuccessBasic
		//  | DiceMarkSuk
		//  | DiceDiscSuk
		//  | DiceRerollSuk
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//  SuccessThreshold
		//| SuccessMultiplier
		//| SuccessBasic
		//| DiceMarkSuk
		//| DiceDiscSuk
		//| DiceRerollSuk
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//SuccessThreshold
		public RuleCall getSuccessThresholdParserRuleCall_0() { return cSuccessThresholdParserRuleCall_0; }
		
		//SuccessMultiplier
		public RuleCall getSuccessMultiplierParserRuleCall_1() { return cSuccessMultiplierParserRuleCall_1; }
		
		//SuccessBasic
		public RuleCall getSuccessBasicParserRuleCall_2() { return cSuccessBasicParserRuleCall_2; }
		
		//DiceMarkSuk
		public RuleCall getDiceMarkSukParserRuleCall_3() { return cDiceMarkSukParserRuleCall_3; }
		
		//DiceDiscSuk
		public RuleCall getDiceDiscSukParserRuleCall_4() { return cDiceDiscSukParserRuleCall_4; }
		
		//DiceRerollSuk
		public RuleCall getDiceRerollSukParserRuleCall_5() { return cDiceRerollSukParserRuleCall_5; }
	}
	public class MarkThresholdElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MarkThreshold");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cWiecejNizKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cMniejNizKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cNumAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNumNumParserRuleCall_1_0 = (RuleCall)cNumAssignment_1.eContents().get(0);
		
		//MarkThreshold returns MarkThan:
		//    ('wiecej niz' | 'mniej niz') num=Num
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('wiecej niz' | 'mniej niz') num=Num
		public Group getGroup() { return cGroup; }
		
		//('wiecej niz' | 'mniej niz')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'wiecej niz'
		public Keyword getWiecejNizKeyword_0_0() { return cWiecejNizKeyword_0_0; }
		
		//'mniej niz'
		public Keyword getMniejNizKeyword_0_1() { return cMniejNizKeyword_0_1; }
		
		//num=Num
		public Assignment getNumAssignment_1() { return cNumAssignment_1; }
		
		//Num
		public RuleCall getNumNumParserRuleCall_1_0() { return cNumNumParserRuleCall_1_0; }
	}
	public class MarkHighestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MarkHighest");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cNajwyzszeKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cNajnizszeKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//MarkHighest returns MarkHigh:
		//    ('najwyzsze' | 'najnizsze')
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('najwyzsze' | 'najnizsze')
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'najwyzsze'
		public Keyword getNajwyzszeKeyword_0() { return cNajwyzszeKeyword_0; }
		
		//'najnizsze'
		public Keyword getNajnizszeKeyword_1() { return cNajnizszeKeyword_1; }
	}
	public class MarkPositionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MarkPosition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cFirstlastAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cFirstlastFirstLastParserRuleCall_0_0 = (RuleCall)cFirstlastAssignment_0.eContents().get(0);
		private final Assignment cNumAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNumNumParserRuleCall_1_0 = (RuleCall)cNumAssignment_1.eContents().get(0);
		
		//MarkPosition returns MarkKol:
		//    firstlast=FirstLast num=Num
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//firstlast=FirstLast num=Num
		public Group getGroup() { return cGroup; }
		
		//firstlast=FirstLast
		public Assignment getFirstlastAssignment_0() { return cFirstlastAssignment_0; }
		
		//FirstLast
		public RuleCall getFirstlastFirstLastParserRuleCall_0_0() { return cFirstlastFirstLastParserRuleCall_0_0; }
		
		//num=Num
		public Assignment getNumAssignment_1() { return cNumAssignment_1; }
		
		//Num
		public RuleCall getNumNumParserRuleCall_1_0() { return cNumNumParserRuleCall_1_0; }
	}
	public class MarkValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.MarkValue");
		private final Assignment cNumAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNumNumParserRuleCall_0 = (RuleCall)cNumAssignment.eContents().get(0);
		
		//MarkValue returns MarkNum:
		//    num=Num
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//num=Num
		public Assignment getNumAssignment() { return cNumAssignment; }
		
		//Num
		public RuleCall getNumNumParserRuleCall_0() { return cNumNumParserRuleCall_0; }
	}
	public class MarkElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Mark");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMarkThresholdParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cMarkHighestParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cMarkPositionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cMarkValueParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Mark returns Mark:
		//    MarkThreshold
		//  | MarkHighest
		//  | MarkPosition
		//  | MarkValue
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//  MarkThreshold
		//| MarkHighest
		//| MarkPosition
		//| MarkValue
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//MarkThreshold
		public RuleCall getMarkThresholdParserRuleCall_0() { return cMarkThresholdParserRuleCall_0; }
		
		//MarkHighest
		public RuleCall getMarkHighestParserRuleCall_1() { return cMarkHighestParserRuleCall_1; }
		
		//MarkPosition
		public RuleCall getMarkPositionParserRuleCall_2() { return cMarkPositionParserRuleCall_2; }
		
		//MarkValue
		public RuleCall getMarkValueParserRuleCall_3() { return cMarkValueParserRuleCall_3; }
	}
	public class DiscardThresholdElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DiscardThreshold");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cWiecejNizKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cMniejNizKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cNumAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNumNumParserRuleCall_1_0 = (RuleCall)cNumAssignment_1.eContents().get(0);
		
		//DiscardThreshold returns DiscardThan:
		//    ('wiecej niz' | 'mniej niz') num=Num
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('wiecej niz' | 'mniej niz') num=Num
		public Group getGroup() { return cGroup; }
		
		//('wiecej niz' | 'mniej niz')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'wiecej niz'
		public Keyword getWiecejNizKeyword_0_0() { return cWiecejNizKeyword_0_0; }
		
		//'mniej niz'
		public Keyword getMniejNizKeyword_0_1() { return cMniejNizKeyword_0_1; }
		
		//num=Num
		public Assignment getNumAssignment_1() { return cNumAssignment_1; }
		
		//Num
		public RuleCall getNumNumParserRuleCall_1_0() { return cNumNumParserRuleCall_1_0; }
	}
	public class DiscardHighestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DiscardHighest");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cNajwyzszeKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cNajnizszeKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//DiscardHighest returns DiscardHigh:
		//    ('najwyzsze' | 'najnizsze')
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('najwyzsze' | 'najnizsze')
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'najwyzsze'
		public Keyword getNajwyzszeKeyword_0() { return cNajwyzszeKeyword_0; }
		
		//'najnizsze'
		public Keyword getNajnizszeKeyword_1() { return cNajnizszeKeyword_1; }
	}
	public class DiscardPositionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DiscardPosition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cFirstlastAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cFirstlastFirstLastParserRuleCall_0_0 = (RuleCall)cFirstlastAssignment_0.eContents().get(0);
		private final Assignment cNumAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNumNumParserRuleCall_1_0 = (RuleCall)cNumAssignment_1.eContents().get(0);
		
		//DiscardPosition returns DiscardKol:
		//    firstlast=FirstLast num=Num
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//firstlast=FirstLast num=Num
		public Group getGroup() { return cGroup; }
		
		//firstlast=FirstLast
		public Assignment getFirstlastAssignment_0() { return cFirstlastAssignment_0; }
		
		//FirstLast
		public RuleCall getFirstlastFirstLastParserRuleCall_0_0() { return cFirstlastFirstLastParserRuleCall_0_0; }
		
		//num=Num
		public Assignment getNumAssignment_1() { return cNumAssignment_1; }
		
		//Num
		public RuleCall getNumNumParserRuleCall_1_0() { return cNumNumParserRuleCall_1_0; }
	}
	public class DiscardValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DiscardValue");
		private final Assignment cNumAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNumNumParserRuleCall_0 = (RuleCall)cNumAssignment.eContents().get(0);
		
		//DiscardValue returns DiscardNum:
		//    num=Num
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//num=Num
		public Assignment getNumAssignment() { return cNumAssignment; }
		
		//Num
		public RuleCall getNumNumParserRuleCall_0() { return cNumNumParserRuleCall_0; }
	}
	public class DiscardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Discard");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cDiscardThresholdParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cDiscardHighestParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cDiscardPositionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cDiscardValueParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Discard returns Discard:
		//    DiscardThreshold
		//  | DiscardHighest
		//  | DiscardPosition
		//  | DiscardValue
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//  DiscardThreshold
		//| DiscardHighest
		//| DiscardPosition
		//| DiscardValue
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//DiscardThreshold
		public RuleCall getDiscardThresholdParserRuleCall_0() { return cDiscardThresholdParserRuleCall_0; }
		
		//DiscardHighest
		public RuleCall getDiscardHighestParserRuleCall_1() { return cDiscardHighestParserRuleCall_1; }
		
		//DiscardPosition
		public RuleCall getDiscardPositionParserRuleCall_2() { return cDiscardPositionParserRuleCall_2; }
		
		//DiscardValue
		public RuleCall getDiscardValueParserRuleCall_3() { return cDiscardValueParserRuleCall_3; }
	}
	public class RerollThresholdElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RerollThreshold");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cWiecejNizKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cMniejNizKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Assignment cNumAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNumNumParserRuleCall_1_0 = (RuleCall)cNumAssignment_1.eContents().get(0);
		
		//RerollThreshold returns RerollThan:
		//    ('wiecej niz' | 'mniej niz') num=Num
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('wiecej niz' | 'mniej niz') num=Num
		public Group getGroup() { return cGroup; }
		
		//('wiecej niz' | 'mniej niz')
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//'wiecej niz'
		public Keyword getWiecejNizKeyword_0_0() { return cWiecejNizKeyword_0_0; }
		
		//'mniej niz'
		public Keyword getMniejNizKeyword_0_1() { return cMniejNizKeyword_0_1; }
		
		//num=Num
		public Assignment getNumAssignment_1() { return cNumAssignment_1; }
		
		//Num
		public RuleCall getNumNumParserRuleCall_1_0() { return cNumNumParserRuleCall_1_0; }
	}
	public class RerollHighestElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RerollHighest");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cNajwyzszeKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cNajnizszeKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//RerollHighest returns RerollHigh:
		//    ('najwyzsze' | 'najnizsze')
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//('najwyzsze' | 'najnizsze')
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'najwyzsze'
		public Keyword getNajwyzszeKeyword_0() { return cNajwyzszeKeyword_0; }
		
		//'najnizsze'
		public Keyword getNajnizszeKeyword_1() { return cNajnizszeKeyword_1; }
	}
	public class RerollPositionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RerollPosition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cFirstlastAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cFirstlastFirstLastParserRuleCall_0_0 = (RuleCall)cFirstlastAssignment_0.eContents().get(0);
		private final Assignment cNumAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNumNumParserRuleCall_1_0 = (RuleCall)cNumAssignment_1.eContents().get(0);
		
		//RerollPosition returns RerollKol:
		//    firstlast=FirstLast num=Num
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//firstlast=FirstLast num=Num
		public Group getGroup() { return cGroup; }
		
		//firstlast=FirstLast
		public Assignment getFirstlastAssignment_0() { return cFirstlastAssignment_0; }
		
		//FirstLast
		public RuleCall getFirstlastFirstLastParserRuleCall_0_0() { return cFirstlastFirstLastParserRuleCall_0_0; }
		
		//num=Num
		public Assignment getNumAssignment_1() { return cNumAssignment_1; }
		
		//Num
		public RuleCall getNumNumParserRuleCall_1_0() { return cNumNumParserRuleCall_1_0; }
	}
	public class RerollValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RerollValue");
		private final Assignment cNumAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNumNumParserRuleCall_0 = (RuleCall)cNumAssignment.eContents().get(0);
		
		//RerollValue returns RerollNum:
		//    num=Num
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//num=Num
		public Assignment getNumAssignment() { return cNumAssignment; }
		
		//Num
		public RuleCall getNumNumParserRuleCall_0() { return cNumNumParserRuleCall_0; }
	}
	public class RerollElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Reroll");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cRerollThresholdParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cRerollHighestParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cRerollPositionParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cRerollValueParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Reroll returns Reroll:
		//    RerollThreshold
		//  | RerollHighest
		//  | RerollPosition
		//  | RerollValue
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//  RerollThreshold
		//| RerollHighest
		//| RerollPosition
		//| RerollValue
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//RerollThreshold
		public RuleCall getRerollThresholdParserRuleCall_0() { return cRerollThresholdParserRuleCall_0; }
		
		//RerollHighest
		public RuleCall getRerollHighestParserRuleCall_1() { return cRerollHighestParserRuleCall_1; }
		
		//RerollPosition
		public RuleCall getRerollPositionParserRuleCall_2() { return cRerollPositionParserRuleCall_2; }
		
		//RerollValue
		public RuleCall getRerollValueParserRuleCall_3() { return cRerollValueParserRuleCall_3; }
	}
	public class NumElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Num");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNumKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cValueKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueEIntParserRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Num returns Num:
		//    'Num' '{' 'value' value=EInt '}'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'Num' '{' 'value' value=EInt '}'
		public Group getGroup() { return cGroup; }
		
		//'Num'
		public Keyword getNumKeyword_0() { return cNumKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//'value'
		public Keyword getValueKeyword_2() { return cValueKeyword_2; }
		
		//value=EInt
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//EInt
		public RuleCall getValueEIntParserRuleCall_3_0() { return cValueEIntParserRuleCall_3_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	public class FirstLastElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.FirstLast");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cFIRSTKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cLASTKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//FirstLast returns FirstLast:
		//    'FIRST' | 'LAST'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'FIRST' | 'LAST'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'FIRST'
		public Keyword getFIRSTKeyword_0() { return cFIRSTKeyword_0; }
		
		//'LAST'
		public Keyword getLASTKeyword_1() { return cLASTKeyword_1; }
	}
	public class OperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Operator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cPlusSignKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cHyphenMinusKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cAsteriskKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		private final Keyword cSolidusKeyword_3 = (Keyword)cAlternatives.eContents().get(3);
		private final Keyword cRazyKeyword_4 = (Keyword)cAlternatives.eContents().get(4);
		
		//Operator returns Operator:
		//    '+' | '-' | '*' | '/' | 'razy'
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'+' | '-' | '*' | '/' | 'razy'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'+'
		public Keyword getPlusSignKeyword_0() { return cPlusSignKeyword_0; }
		
		//'-'
		public Keyword getHyphenMinusKeyword_1() { return cHyphenMinusKeyword_1; }
		
		//'*'
		public Keyword getAsteriskKeyword_2() { return cAsteriskKeyword_2; }
		
		//'/'
		public Keyword getSolidusKeyword_3() { return cSolidusKeyword_3; }
		
		//'razy'
		public Keyword getRazyKeyword_4() { return cRazyKeyword_4; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.EString");
		private final RuleCall cSTRINGTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall() { return cSTRINGTerminalRuleCall; }
	}
	
	
	private final StatementElements pStatement;
	private final SumujElements pSumuj;
	private final SukcesyElements pSukcesy;
	private final DiceExprSumElements pDiceExprSum;
	private final DiceExprSukElements pDiceExprSuk;
	private final MulExprElements pMulExpr;
	private final FormElements pForm;
	private final SingleDiceElements pSingleDice;
	private final MultiDiceElements pMultiDice;
	private final DiceElements pDice;
	private final ExplosionRuleElements pExplosionRule;
	private final DiceMarkSumElements pDiceMarkSum;
	private final DiceDiscSumElements pDiceDiscSum;
	private final DiceRerollSumElements pDiceRerollSum;
	private final RuleSumElements pRuleSum;
	private final SuccessThresholdElements pSuccessThreshold;
	private final SuccessMultiplierElements pSuccessMultiplier;
	private final SuccessBasicElements pSuccessBasic;
	private final DiceMarkSukElements pDiceMarkSuk;
	private final DiceDiscSukElements pDiceDiscSuk;
	private final DiceRerollSukElements pDiceRerollSuk;
	private final RuleSukElements pRuleSuk;
	private final MarkThresholdElements pMarkThreshold;
	private final MarkHighestElements pMarkHighest;
	private final MarkPositionElements pMarkPosition;
	private final MarkValueElements pMarkValue;
	private final MarkElements pMark;
	private final DiscardThresholdElements pDiscardThreshold;
	private final DiscardHighestElements pDiscardHighest;
	private final DiscardPositionElements pDiscardPosition;
	private final DiscardValueElements pDiscardValue;
	private final DiscardElements pDiscard;
	private final RerollThresholdElements pRerollThreshold;
	private final RerollHighestElements pRerollHighest;
	private final RerollPositionElements pRerollPosition;
	private final RerollValueElements pRerollValue;
	private final RerollElements pReroll;
	private final NumElements pNum;
	private final FirstLastElements pFirstLast;
	private final OperatorElements pOperator;
	private final EIntElements pEInt;
	private final EStringElements pEString;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pStatement = new StatementElements();
		this.pSumuj = new SumujElements();
		this.pSukcesy = new SukcesyElements();
		this.pDiceExprSum = new DiceExprSumElements();
		this.pDiceExprSuk = new DiceExprSukElements();
		this.pMulExpr = new MulExprElements();
		this.pForm = new FormElements();
		this.pSingleDice = new SingleDiceElements();
		this.pMultiDice = new MultiDiceElements();
		this.pDice = new DiceElements();
		this.pExplosionRule = new ExplosionRuleElements();
		this.pDiceMarkSum = new DiceMarkSumElements();
		this.pDiceDiscSum = new DiceDiscSumElements();
		this.pDiceRerollSum = new DiceRerollSumElements();
		this.pRuleSum = new RuleSumElements();
		this.pSuccessThreshold = new SuccessThresholdElements();
		this.pSuccessMultiplier = new SuccessMultiplierElements();
		this.pSuccessBasic = new SuccessBasicElements();
		this.pDiceMarkSuk = new DiceMarkSukElements();
		this.pDiceDiscSuk = new DiceDiscSukElements();
		this.pDiceRerollSuk = new DiceRerollSukElements();
		this.pRuleSuk = new RuleSukElements();
		this.pMarkThreshold = new MarkThresholdElements();
		this.pMarkHighest = new MarkHighestElements();
		this.pMarkPosition = new MarkPositionElements();
		this.pMarkValue = new MarkValueElements();
		this.pMark = new MarkElements();
		this.pDiscardThreshold = new DiscardThresholdElements();
		this.pDiscardHighest = new DiscardHighestElements();
		this.pDiscardPosition = new DiscardPositionElements();
		this.pDiscardValue = new DiscardValueElements();
		this.pDiscard = new DiscardElements();
		this.pRerollThreshold = new RerollThresholdElements();
		this.pRerollHighest = new RerollHighestElements();
		this.pRerollPosition = new RerollPositionElements();
		this.pRerollValue = new RerollValueElements();
		this.pReroll = new RerollElements();
		this.pNum = new NumElements();
		this.pFirstLast = new FirstLastElements();
		this.pOperator = new OperatorElements();
		this.pEInt = new EIntElements();
		this.pEString = new EStringElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Statement returns Stat:
	//    Sumuj | Sukcesy
	//;
	public StatementElements getStatementAccess() {
		return pStatement;
	}
	
	public ParserRule getStatementRule() {
		return getStatementAccess().getRule();
	}
	
	//Sumuj returns SumStatement:
	//    'SUMUJ' diceexprsum+=DiceExprSum ( ';' diceexprsum+=DiceExprSum )* ('.' | ',')?
	//;
	public SumujElements getSumujAccess() {
		return pSumuj;
	}
	
	public ParserRule getSumujRule() {
		return getSumujAccess().getRule();
	}
	
	//Sukcesy returns SuccessStatement:
	//    'SUKCESY' diceexprsuk+=DiceExprSuk ( ';' diceexprsuk+=DiceExprSuk )* ('.' | ',')?
	//;
	public SukcesyElements getSukcesyAccess() {
		return pSukcesy;
	}
	
	public ParserRule getSukcesyRule() {
		return getSukcesyAccess().getRule();
	}
	
	//DiceExprSum returns DiceExprSum:
	//    ('+'|'-')? mulexpr=MulExpr (':' sumrule+=RuleSum (',' sumrule+=RuleSum)*)?
	//;
	public DiceExprSumElements getDiceExprSumAccess() {
		return pDiceExprSum;
	}
	
	public ParserRule getDiceExprSumRule() {
		return getDiceExprSumAccess().getRule();
	}
	
	//DiceExprSuk returns DiceExprSuk:
	//    ('+'|'-')? mulexpr=MulExpr (':' successrule+=RuleSuk (',' successrule+=RuleSuk)*)?
	//;
	public DiceExprSukElements getDiceExprSukAccess() {
		return pDiceExprSuk;
	}
	
	public ParserRule getDiceExprSukRule() {
		return getDiceExprSukAccess().getRule();
	}
	
	//MulExpr returns MulExpr:
	//        formexpr=Form
	//  | '(' formexpr=Form ')' ('razy' num=Num)?
	//;
	public MulExprElements getMulExprAccess() {
		return pMulExpr;
	}
	
	public ParserRule getMulExprRule() {
		return getMulExprAccess().getRule();
	}
	
	//Form returns FormExpr:
	//    left=(Dice) ( operator=Operator right=Num )?
	//;
	public FormElements getFormAccess() {
		return pForm;
	}
	
	public ParserRule getFormRule() {
		return getFormAccess().getRule();
	}
	
	//SingleDice returns SingleDice:
	//    'd' sides=Num
	//;
	public SingleDiceElements getSingleDiceAccess() {
		return pSingleDice;
	}
	
	public ParserRule getSingleDiceRule() {
		return getSingleDiceAccess().getRule();
	}
	
	//MultiDice returns MultiDice:
	//    count=Num 'd' sides=Num
	//;
	public MultiDiceElements getMultiDiceAccess() {
		return pMultiDice;
	}
	
	public ParserRule getMultiDiceRule() {
		return getMultiDiceAccess().getRule();
	}
	
	//Dice returns Dice:
	//    SingleDice | MultiDice
	//;
	public DiceElements getDiceAccess() {
		return pDice;
	}
	
	public ParserRule getDiceRule() {
		return getDiceAccess().getRule();
	}
	
	//ExplosionRule returns ExplosionRule:
	//    ('dodawaj' | 'odejmuj') 'wybuchowe' num=Num
	//;
	public ExplosionRuleElements getExplosionRuleAccess() {
		return pExplosionRule;
	}
	
	public ParserRule getExplosionRuleRule() {
		return getExplosionRuleAccess().getRule();
	}
	
	//DiceMarkSum returns DiceMarkSum:
	//    'oznacz' mark=Mark
	//;
	public DiceMarkSumElements getDiceMarkSumAccess() {
		return pDiceMarkSum;
	}
	
	public ParserRule getDiceMarkSumRule() {
		return getDiceMarkSumAccess().getRule();
	}
	
	//DiceDiscSum returns DiceDiscSum:
	//    'odrzuc' discard=Discard
	//;
	public DiceDiscSumElements getDiceDiscSumAccess() {
		return pDiceDiscSum;
	}
	
	public ParserRule getDiceDiscSumRule() {
		return getDiceDiscSumAccess().getRule();
	}
	
	//DiceRerollSum returns DiceRerollSum:
	//    'przerzuc' reroll=Reroll
	//;
	public DiceRerollSumElements getDiceRerollSumAccess() {
		return pDiceRerollSum;
	}
	
	public ParserRule getDiceRerollSumRule() {
		return getDiceRerollSumAccess().getRule();
	}
	
	//RuleSum returns SumRule:
	//    ExplosionRule
	//  | DiceMarkSum
	//  | DiceDiscSum
	//  | DiceRerollSum
	//;
	public RuleSumElements getRuleSumAccess() {
		return pRuleSum;
	}
	
	public ParserRule getRuleSumRule() {
		return getRuleSumAccess().getRule();
	}
	
	//SuccessThreshold returns SuccessThreshold:
	//    'sukces' ('wiecej niz' | 'mniej niz') num=Num
	//;
	public SuccessThresholdElements getSuccessThresholdAccess() {
		return pSuccessThreshold;
	}
	
	public ParserRule getSuccessThresholdRule() {
		return getSuccessThresholdAccess().getRule();
	}
	
	//SuccessMultiplier returns SuccessMultiplier:
	//    'sukces' num=Num 'razy' mult=Num
	//;
	public SuccessMultiplierElements getSuccessMultiplierAccess() {
		return pSuccessMultiplier;
	}
	
	public ParserRule getSuccessMultiplierRule() {
		return getSuccessMultiplierAccess().getRule();
	}
	
	//SuccessBasic returns SuccessBasic:
	//    'sukces' ('sukces' | num=Num)
	//;
	public SuccessBasicElements getSuccessBasicAccess() {
		return pSuccessBasic;
	}
	
	public ParserRule getSuccessBasicRule() {
		return getSuccessBasicAccess().getRule();
	}
	
	//DiceMarkSuk returns DiceMarkSuk:
	//    'oznacz' mark=Mark
	//;
	public DiceMarkSukElements getDiceMarkSukAccess() {
		return pDiceMarkSuk;
	}
	
	public ParserRule getDiceMarkSukRule() {
		return getDiceMarkSukAccess().getRule();
	}
	
	//DiceDiscSuk returns DiceDiscSuk:
	//    'odrzuc' discard=Discard
	//;
	public DiceDiscSukElements getDiceDiscSukAccess() {
		return pDiceDiscSuk;
	}
	
	public ParserRule getDiceDiscSukRule() {
		return getDiceDiscSukAccess().getRule();
	}
	
	//DiceRerollSuk returns DiceRerollSuk:
	//    'przerzuc' reroll=Reroll
	//;
	public DiceRerollSukElements getDiceRerollSukAccess() {
		return pDiceRerollSuk;
	}
	
	public ParserRule getDiceRerollSukRule() {
		return getDiceRerollSukAccess().getRule();
	}
	
	//RuleSuk returns SuccessRule:
	//    SuccessThreshold
	//  | SuccessMultiplier
	//  | SuccessBasic
	//  | DiceMarkSuk
	//  | DiceDiscSuk
	//  | DiceRerollSuk
	//;
	public RuleSukElements getRuleSukAccess() {
		return pRuleSuk;
	}
	
	public ParserRule getRuleSukRule() {
		return getRuleSukAccess().getRule();
	}
	
	//MarkThreshold returns MarkThan:
	//    ('wiecej niz' | 'mniej niz') num=Num
	//;
	public MarkThresholdElements getMarkThresholdAccess() {
		return pMarkThreshold;
	}
	
	public ParserRule getMarkThresholdRule() {
		return getMarkThresholdAccess().getRule();
	}
	
	//MarkHighest returns MarkHigh:
	//    ('najwyzsze' | 'najnizsze')
	//;
	public MarkHighestElements getMarkHighestAccess() {
		return pMarkHighest;
	}
	
	public ParserRule getMarkHighestRule() {
		return getMarkHighestAccess().getRule();
	}
	
	//MarkPosition returns MarkKol:
	//    firstlast=FirstLast num=Num
	//;
	public MarkPositionElements getMarkPositionAccess() {
		return pMarkPosition;
	}
	
	public ParserRule getMarkPositionRule() {
		return getMarkPositionAccess().getRule();
	}
	
	//MarkValue returns MarkNum:
	//    num=Num
	//;
	public MarkValueElements getMarkValueAccess() {
		return pMarkValue;
	}
	
	public ParserRule getMarkValueRule() {
		return getMarkValueAccess().getRule();
	}
	
	//Mark returns Mark:
	//    MarkThreshold
	//  | MarkHighest
	//  | MarkPosition
	//  | MarkValue
	//;
	public MarkElements getMarkAccess() {
		return pMark;
	}
	
	public ParserRule getMarkRule() {
		return getMarkAccess().getRule();
	}
	
	//DiscardThreshold returns DiscardThan:
	//    ('wiecej niz' | 'mniej niz') num=Num
	//;
	public DiscardThresholdElements getDiscardThresholdAccess() {
		return pDiscardThreshold;
	}
	
	public ParserRule getDiscardThresholdRule() {
		return getDiscardThresholdAccess().getRule();
	}
	
	//DiscardHighest returns DiscardHigh:
	//    ('najwyzsze' | 'najnizsze')
	//;
	public DiscardHighestElements getDiscardHighestAccess() {
		return pDiscardHighest;
	}
	
	public ParserRule getDiscardHighestRule() {
		return getDiscardHighestAccess().getRule();
	}
	
	//DiscardPosition returns DiscardKol:
	//    firstlast=FirstLast num=Num
	//;
	public DiscardPositionElements getDiscardPositionAccess() {
		return pDiscardPosition;
	}
	
	public ParserRule getDiscardPositionRule() {
		return getDiscardPositionAccess().getRule();
	}
	
	//DiscardValue returns DiscardNum:
	//    num=Num
	//;
	public DiscardValueElements getDiscardValueAccess() {
		return pDiscardValue;
	}
	
	public ParserRule getDiscardValueRule() {
		return getDiscardValueAccess().getRule();
	}
	
	//Discard returns Discard:
	//    DiscardThreshold
	//  | DiscardHighest
	//  | DiscardPosition
	//  | DiscardValue
	//;
	public DiscardElements getDiscardAccess() {
		return pDiscard;
	}
	
	public ParserRule getDiscardRule() {
		return getDiscardAccess().getRule();
	}
	
	//RerollThreshold returns RerollThan:
	//    ('wiecej niz' | 'mniej niz') num=Num
	//;
	public RerollThresholdElements getRerollThresholdAccess() {
		return pRerollThreshold;
	}
	
	public ParserRule getRerollThresholdRule() {
		return getRerollThresholdAccess().getRule();
	}
	
	//RerollHighest returns RerollHigh:
	//    ('najwyzsze' | 'najnizsze')
	//;
	public RerollHighestElements getRerollHighestAccess() {
		return pRerollHighest;
	}
	
	public ParserRule getRerollHighestRule() {
		return getRerollHighestAccess().getRule();
	}
	
	//RerollPosition returns RerollKol:
	//    firstlast=FirstLast num=Num
	//;
	public RerollPositionElements getRerollPositionAccess() {
		return pRerollPosition;
	}
	
	public ParserRule getRerollPositionRule() {
		return getRerollPositionAccess().getRule();
	}
	
	//RerollValue returns RerollNum:
	//    num=Num
	//;
	public RerollValueElements getRerollValueAccess() {
		return pRerollValue;
	}
	
	public ParserRule getRerollValueRule() {
		return getRerollValueAccess().getRule();
	}
	
	//Reroll returns Reroll:
	//    RerollThreshold
	//  | RerollHighest
	//  | RerollPosition
	//  | RerollValue
	//;
	public RerollElements getRerollAccess() {
		return pReroll;
	}
	
	public ParserRule getRerollRule() {
		return getRerollAccess().getRule();
	}
	
	//Num returns Num:
	//    'Num' '{' 'value' value=EInt '}'
	//;
	public NumElements getNumAccess() {
		return pNum;
	}
	
	public ParserRule getNumRule() {
		return getNumAccess().getRule();
	}
	
	//FirstLast returns FirstLast:
	//    'FIRST' | 'LAST'
	//;
	public FirstLastElements getFirstLastAccess() {
		return pFirstLast;
	}
	
	public ParserRule getFirstLastRule() {
		return getFirstLastAccess().getRule();
	}
	
	//Operator returns Operator:
	//    '+' | '-' | '*' | '/' | 'razy'
	//;
	public OperatorElements getOperatorAccess() {
		return pOperator;
	}
	
	public ParserRule getOperatorRule() {
		return getOperatorAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT
	//;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING
	//;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
